name: myTest
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          build-root-directory: app
      - run: |
          cd app
          make build
